//import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "../components/layout/AppSidebar/app-sidebar";
import { Separator } from "@/components/ui/separator";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { CreditCard, Notebook, ShoppingBag, User } from "lucide-react";
import { Breadcrumbs } from "../components/layout/Breadcrumb/breadcrumb";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
//});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// Menu items.
const items = [
  {
    title: "Users",
    url: "/users",
    icon: User,
  },
  {
    title: "Products",
    url: "/products",
    icon: Notebook,
  },
  {
    title: "Orders",
    url: "/orders",
    icon: ShoppingBag,
  },
  {
    title: "Payments",
    url: "/payments",
    icon: CreditCard,
  },
  // {
  //   title: "Settings",
  //   url: "#",
  //   icon: Settings,
  // },
];

export default function RootLayout({
  // это компонент отрисовывает html и body
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <main>
              <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4">
                <SidebarTrigger className="-ml-1" />
                <Separator
                  orientation="vertical"
                  className="mr-2 data-[orientation=vertical]:h-4"
                />
                <Breadcrumbs/>
              </header>
              {children}
              {/* children это дочерние компооненты отображающие содержимое каждой страницы приложения */}
            </main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}

//Lauout это шаблон который общий и  оборачивает все страницы приложения
